detection:
  confidence_threshold: 0.2
  nms_iou_threshold: 0.1

source:
  - [642, 784]
  - [1960, 881]
  - [1146, 1009]
  - [-161, 852]

target:
  width: 300
  height: 260
  reference: "../images/base_image_sdu_01.png" 